//! Emits a Windows Node-API forwarder Zig source file.
//!
//! The generated forwarder defines local `napi_*` / `node_api_*` symbols that
//! lazily resolve to runtime-provided implementations via `GetProcAddress`.
//! This intentionally aims to match node-gyp delayed host lookup behavior:
//! https://github.com/nodejs/node-gyp/blob/main/src/win_delay_load_hook.cc

const std = @import("std");
const napi = @import("tokota").napi;

comptime {
    @import("tokota").exportModule(@This());
}

pub fn main() !void {
    try emit();
}

pub fn emit() !void {
    const decls = @typeInfo(napi).@"struct".decls;

    const symbols = comptime blk: {
        var symbols: [decls.len][]const u8 = undefined;
        var len = 0;

        for (decls) |d| {
            switch (@typeInfo(@TypeOf(@field(napi, d.name)))) {
                .@"fn" => {
                    symbols[len] = d.name;
                    len += 1;
                },
                else => {},
            }
        }

        break :blk symbols[0..len].*;
    };

    const allo = std.heap.smp_allocator;

    var io_threaded = std.Io.Threaded.init(allo, .{ .environ = .empty });
    defer io_threaded.deinit();

    const io = io_threaded.ioBasic();

    var buf: [2048]u8 = undefined;
    var std_out = std.Io.File.stdout().writer(io, &buf);

    try emitHeader(&std_out.interface);
    try emitSymbolsStruct(&std_out.interface, symbols);
    try emitWrappers(&std_out.interface, symbols);

    try std_out.interface.flush();
}

fn emitHeader(w: *std.Io.Writer) !void {
    try w.writeAll(
        \\// GENERATED by _build/windows/emit_napi_proxy.zig
        \\// DO NOT EDIT MANUALLY
        \\const std = @import("std");
        \\const n = @import("tokota").napi;
        \\
        \\const HMODULE = ?*anyopaque;
        \\extern "kernel32" fn GetModuleHandleA(name: ?[*:0]const u8) callconv(.winapi) HMODULE;
        \\extern "kernel32" fn GetProcAddress(module: HMODULE, proc: [*:0]const u8) callconv(.winapi) ?*anyopaque;
        \\
        \\var symbols_lock: std.atomic.Mutex = .unlocked;
        \\
        \\fn hostModule() HMODULE {
        \\    if (GetModuleHandleA("libnode.dll")) |module| return module;
        \\    if (GetModuleHandleA(null)) |module| return module;
        \\    @panic("Failed to obtain host module handle");
        \\}
        \\
        \\fn lookup(comptime Fn: type, module: HMODULE, comptime symbol: [*:0]const u8) *const Fn {
        \\    const proc = GetProcAddress(module, symbol) orelse std.debug.panic(
        \\        "Missing required Node-API symbol: {s}",
        \\        .{symbol},
        \\    );
        \\    return @ptrCast(@alignCast(proc));
        \\}
        \\
        \\fn resolve(
        \\    comptime Fn: type,
        \\    comptime symbol: [*:0]const u8,
        \\    slot: *?*const Fn,
        \\) *const Fn {
        \\    if (slot.*) |ptr| return ptr;
        \\
        \\    while (!symbols_lock.tryLock()) std.atomic.spinLoopHint();
        \\    defer symbols_lock.unlock();
        \\
        \\    if (slot.*) |ptr| return ptr;
        \\
        \\    const ptr = lookup(Fn, hostModule(), symbol);
        \\    slot.* = ptr;
        \\    return ptr;
        \\}
        \\
    );
}

fn emitSymbolsStruct(w: *std.Io.Writer, comptime symbols: anytype) !void {
    try w.writeAll(
        \\const symbols = struct {
        \\
    );

    inline for (symbols) |name| try w.print(
        \\    var {s}: ?*const @TypeOf(n.{s}) = null;
        \\
    , .{ name, name });

    try w.writeAll(
        \\};
        \\
    );
}

fn emitWrappers(w: *std.Io.Writer, comptime symbols: anytype) !void {
    @setEvalBranchQuota(10_000);

    inline for (symbols) |name| {
        const fn_info = @typeInfo(@TypeOf(@field(napi, name))).@"fn";

        try w.print("pub export fn {s}(\n", .{name});

        inline for (fn_info.params, 0..) |param, i| {
            const p_type = param.type orelse @compileError(std.fmt.comptimePrint(
                "Expected concrete parameter type for symbol: {s}",
                .{name},
            ));

            _ = p_type;
            try w.print(
                "    arg{d}: @typeInfo(@TypeOf(n.{s})).@\"fn\".params[{d}].type.?,\n",
                .{ i, name, i },
            );
        }

        try w.print(
            ") @typeInfo(@TypeOf(n.{s})).@\"fn\".return_type.? {{\n",
            .{name},
        );

        try w.print(
            "    const ptr = resolve(@TypeOf(n.{s}), \"{s}\", &symbols.{s});\n",
            .{ name, name, name },
        );

        const ret = fn_info.return_type orelse @compileError(std.fmt.comptimePrint(
            "Expected concrete return type for symbol: {s}",
            .{name},
        ));

        if (ret == void) {
            try w.writeAll("    ptr(");
        } else {
            try w.writeAll("    return ptr(");
        }

        inline for (fn_info.params, 0..) |_, i| {
            if (i != 0) try w.writeAll(", ");
            try w.print("arg{d}", .{i});
        }

        try w.writeAll(
            \\);
            \\}
            \\
        );
    }
}
