// GENERATED by _build/windows/emit_napi_proxy.zig
// DO NOT EDIT MANUALLY
const std = @import("std");
const n = @import("tokota").napi;

const HMODULE = ?*anyopaque;
extern "kernel32" fn GetModuleHandleA(name: ?[*:0]const u8) callconv(.winapi) HMODULE;
extern "kernel32" fn GetProcAddress(module: HMODULE, proc: [*:0]const u8) callconv(.winapi) ?*anyopaque;

var symbols_lock: std.atomic.Mutex = .unlocked;

fn hostModule() HMODULE {
    if (GetModuleHandleA("libnode.dll")) |module| return module;
    if (GetModuleHandleA(null)) |module| return module;
    @panic("Failed to obtain host module handle");
}

fn lookup(comptime Fn: type, module: HMODULE, comptime symbol: [*:0]const u8) *const Fn {
    const proc = GetProcAddress(module, symbol) orelse std.debug.panic(
        "Missing required Node-API symbol: {s}",
        .{symbol},
    );
    return @ptrCast(@alignCast(proc));
}

fn resolve(
    comptime Fn: type,
    comptime symbol: [*:0]const u8,
    slot: *?*const Fn,
) *const Fn {
    if (slot.*) |ptr| return ptr;

    while (!symbols_lock.tryLock()) std.atomic.spinLoopHint();
    defer symbols_lock.unlock();

    if (slot.*) |ptr| return ptr;

    const ptr = lookup(Fn, hostModule(), symbol);
    slot.* = ptr;
    return ptr;
}
const symbols = struct {
    var napi_acquire_threadsafe_function: ?*const @TypeOf(n.napi_acquire_threadsafe_function) = null;
    var napi_add_async_cleanup_hook: ?*const @TypeOf(n.napi_add_async_cleanup_hook) = null;
    var napi_add_env_cleanup_hook: ?*const @TypeOf(n.napi_add_env_cleanup_hook) = null;
    var napi_add_finalizer: ?*const @TypeOf(n.napi_add_finalizer) = null;
    var napi_adjust_external_memory: ?*const @TypeOf(n.napi_adjust_external_memory) = null;
    var napi_async_destroy: ?*const @TypeOf(n.napi_async_destroy) = null;
    var napi_async_init: ?*const @TypeOf(n.napi_async_init) = null;
    var napi_call_function: ?*const @TypeOf(n.napi_call_function) = null;
    var napi_call_threadsafe_function: ?*const @TypeOf(n.napi_call_threadsafe_function) = null;
    var napi_cancel_async_work: ?*const @TypeOf(n.napi_cancel_async_work) = null;
    var napi_check_object_type_tag: ?*const @TypeOf(n.napi_check_object_type_tag) = null;
    var napi_close_callback_scope: ?*const @TypeOf(n.napi_close_callback_scope) = null;
    var napi_close_escapable_handle_scope: ?*const @TypeOf(n.napi_close_escapable_handle_scope) = null;
    var napi_close_handle_scope: ?*const @TypeOf(n.napi_close_handle_scope) = null;
    var napi_coerce_to_bool: ?*const @TypeOf(n.napi_coerce_to_bool) = null;
    var napi_coerce_to_number: ?*const @TypeOf(n.napi_coerce_to_number) = null;
    var napi_coerce_to_object: ?*const @TypeOf(n.napi_coerce_to_object) = null;
    var napi_coerce_to_string: ?*const @TypeOf(n.napi_coerce_to_string) = null;
    var napi_create_array: ?*const @TypeOf(n.napi_create_array) = null;
    var napi_create_array_with_length: ?*const @TypeOf(n.napi_create_array_with_length) = null;
    var napi_create_arraybuffer: ?*const @TypeOf(n.napi_create_arraybuffer) = null;
    var napi_create_async_work: ?*const @TypeOf(n.napi_create_async_work) = null;
    var napi_create_bigint_int64: ?*const @TypeOf(n.napi_create_bigint_int64) = null;
    var napi_create_bigint_uint64: ?*const @TypeOf(n.napi_create_bigint_uint64) = null;
    var napi_create_bigint_words: ?*const @TypeOf(n.napi_create_bigint_words) = null;
    var napi_create_buffer: ?*const @TypeOf(n.napi_create_buffer) = null;
    var napi_create_buffer_copy: ?*const @TypeOf(n.napi_create_buffer_copy) = null;
    var napi_create_dataview: ?*const @TypeOf(n.napi_create_dataview) = null;
    var napi_create_date: ?*const @TypeOf(n.napi_create_date) = null;
    var napi_create_double: ?*const @TypeOf(n.napi_create_double) = null;
    var napi_create_error: ?*const @TypeOf(n.napi_create_error) = null;
    var napi_create_external: ?*const @TypeOf(n.napi_create_external) = null;
    var napi_create_external_arraybuffer: ?*const @TypeOf(n.napi_create_external_arraybuffer) = null;
    var napi_create_external_buffer: ?*const @TypeOf(n.napi_create_external_buffer) = null;
    var napi_create_function: ?*const @TypeOf(n.napi_create_function) = null;
    var napi_create_int32: ?*const @TypeOf(n.napi_create_int32) = null;
    var napi_create_int64: ?*const @TypeOf(n.napi_create_int64) = null;
    var napi_create_object: ?*const @TypeOf(n.napi_create_object) = null;
    var napi_create_promise: ?*const @TypeOf(n.napi_create_promise) = null;
    var napi_create_range_error: ?*const @TypeOf(n.napi_create_range_error) = null;
    var napi_create_reference: ?*const @TypeOf(n.napi_create_reference) = null;
    var napi_create_string_latin1: ?*const @TypeOf(n.napi_create_string_latin1) = null;
    var napi_create_string_utf16: ?*const @TypeOf(n.napi_create_string_utf16) = null;
    var napi_create_string_utf8: ?*const @TypeOf(n.napi_create_string_utf8) = null;
    var napi_create_symbol: ?*const @TypeOf(n.napi_create_symbol) = null;
    var napi_create_threadsafe_function: ?*const @TypeOf(n.napi_create_threadsafe_function) = null;
    var napi_create_type_error: ?*const @TypeOf(n.napi_create_type_error) = null;
    var napi_create_typedarray: ?*const @TypeOf(n.napi_create_typedarray) = null;
    var napi_create_uint32: ?*const @TypeOf(n.napi_create_uint32) = null;
    var napi_define_class: ?*const @TypeOf(n.napi_define_class) = null;
    var napi_define_properties: ?*const @TypeOf(n.napi_define_properties) = null;
    var napi_delete_async_work: ?*const @TypeOf(n.napi_delete_async_work) = null;
    var napi_delete_element: ?*const @TypeOf(n.napi_delete_element) = null;
    var napi_delete_property: ?*const @TypeOf(n.napi_delete_property) = null;
    var napi_delete_reference: ?*const @TypeOf(n.napi_delete_reference) = null;
    var napi_detach_arraybuffer: ?*const @TypeOf(n.napi_detach_arraybuffer) = null;
    var napi_escape_handle: ?*const @TypeOf(n.napi_escape_handle) = null;
    var napi_fatal_error: ?*const @TypeOf(n.napi_fatal_error) = null;
    var napi_fatal_exception: ?*const @TypeOf(n.napi_fatal_exception) = null;
    var napi_get_all_property_names: ?*const @TypeOf(n.napi_get_all_property_names) = null;
    var napi_get_and_clear_last_exception: ?*const @TypeOf(n.napi_get_and_clear_last_exception) = null;
    var napi_get_array_length: ?*const @TypeOf(n.napi_get_array_length) = null;
    var napi_get_arraybuffer_info: ?*const @TypeOf(n.napi_get_arraybuffer_info) = null;
    var napi_get_boolean: ?*const @TypeOf(n.napi_get_boolean) = null;
    var napi_get_buffer_info: ?*const @TypeOf(n.napi_get_buffer_info) = null;
    var napi_get_cb_info: ?*const @TypeOf(n.napi_get_cb_info) = null;
    var napi_get_dataview_info: ?*const @TypeOf(n.napi_get_dataview_info) = null;
    var napi_get_date_value: ?*const @TypeOf(n.napi_get_date_value) = null;
    var napi_get_element: ?*const @TypeOf(n.napi_get_element) = null;
    var napi_get_global: ?*const @TypeOf(n.napi_get_global) = null;
    var napi_get_instance_data: ?*const @TypeOf(n.napi_get_instance_data) = null;
    var napi_get_last_error_info: ?*const @TypeOf(n.napi_get_last_error_info) = null;
    var napi_get_named_property: ?*const @TypeOf(n.napi_get_named_property) = null;
    var napi_get_new_target: ?*const @TypeOf(n.napi_get_new_target) = null;
    var napi_get_null: ?*const @TypeOf(n.napi_get_null) = null;
    var napi_get_property: ?*const @TypeOf(n.napi_get_property) = null;
    var napi_get_property_names: ?*const @TypeOf(n.napi_get_property_names) = null;
    var napi_get_prototype: ?*const @TypeOf(n.napi_get_prototype) = null;
    var napi_get_reference_value: ?*const @TypeOf(n.napi_get_reference_value) = null;
    var napi_get_threadsafe_function_context: ?*const @TypeOf(n.napi_get_threadsafe_function_context) = null;
    var napi_get_typedarray_info: ?*const @TypeOf(n.napi_get_typedarray_info) = null;
    var napi_get_undefined: ?*const @TypeOf(n.napi_get_undefined) = null;
    var napi_get_value_bigint_int64: ?*const @TypeOf(n.napi_get_value_bigint_int64) = null;
    var napi_get_value_bigint_uint64: ?*const @TypeOf(n.napi_get_value_bigint_uint64) = null;
    var napi_get_value_bigint_words: ?*const @TypeOf(n.napi_get_value_bigint_words) = null;
    var napi_get_value_bool: ?*const @TypeOf(n.napi_get_value_bool) = null;
    var napi_get_value_double: ?*const @TypeOf(n.napi_get_value_double) = null;
    var napi_get_value_external: ?*const @TypeOf(n.napi_get_value_external) = null;
    var napi_get_value_int32: ?*const @TypeOf(n.napi_get_value_int32) = null;
    var napi_get_value_int64: ?*const @TypeOf(n.napi_get_value_int64) = null;
    var napi_get_value_string_latin1: ?*const @TypeOf(n.napi_get_value_string_latin1) = null;
    var napi_get_value_string_utf16: ?*const @TypeOf(n.napi_get_value_string_utf16) = null;
    var napi_get_value_string_utf8: ?*const @TypeOf(n.napi_get_value_string_utf8) = null;
    var napi_get_value_uint32: ?*const @TypeOf(n.napi_get_value_uint32) = null;
    var napi_has_element: ?*const @TypeOf(n.napi_has_element) = null;
    var napi_has_named_property: ?*const @TypeOf(n.napi_has_named_property) = null;
    var napi_has_own_property: ?*const @TypeOf(n.napi_has_own_property) = null;
    var napi_has_property: ?*const @TypeOf(n.napi_has_property) = null;
    var napi_instanceof: ?*const @TypeOf(n.napi_instanceof) = null;
    var napi_is_array: ?*const @TypeOf(n.napi_is_array) = null;
    var napi_is_arraybuffer: ?*const @TypeOf(n.napi_is_arraybuffer) = null;
    var napi_is_buffer: ?*const @TypeOf(n.napi_is_buffer) = null;
    var napi_is_dataview: ?*const @TypeOf(n.napi_is_dataview) = null;
    var napi_is_date: ?*const @TypeOf(n.napi_is_date) = null;
    var napi_is_detached_arraybuffer: ?*const @TypeOf(n.napi_is_detached_arraybuffer) = null;
    var napi_is_error: ?*const @TypeOf(n.napi_is_error) = null;
    var napi_is_exception_pending: ?*const @TypeOf(n.napi_is_exception_pending) = null;
    var napi_is_promise: ?*const @TypeOf(n.napi_is_promise) = null;
    var napi_is_typedarray: ?*const @TypeOf(n.napi_is_typedarray) = null;
    var napi_make_callback: ?*const @TypeOf(n.napi_make_callback) = null;
    var napi_new_instance: ?*const @TypeOf(n.napi_new_instance) = null;
    var napi_object_freeze: ?*const @TypeOf(n.napi_object_freeze) = null;
    var napi_object_seal: ?*const @TypeOf(n.napi_object_seal) = null;
    var napi_open_callback_scope: ?*const @TypeOf(n.napi_open_callback_scope) = null;
    var napi_open_escapable_handle_scope: ?*const @TypeOf(n.napi_open_escapable_handle_scope) = null;
    var napi_open_handle_scope: ?*const @TypeOf(n.napi_open_handle_scope) = null;
    var napi_queue_async_work: ?*const @TypeOf(n.napi_queue_async_work) = null;
    var napi_ref_threadsafe_function: ?*const @TypeOf(n.napi_ref_threadsafe_function) = null;
    var napi_reference_ref: ?*const @TypeOf(n.napi_reference_ref) = null;
    var napi_reference_unref: ?*const @TypeOf(n.napi_reference_unref) = null;
    var napi_reject_deferred: ?*const @TypeOf(n.napi_reject_deferred) = null;
    var napi_release_threadsafe_function: ?*const @TypeOf(n.napi_release_threadsafe_function) = null;
    var napi_remove_async_cleanup_hook: ?*const @TypeOf(n.napi_remove_async_cleanup_hook) = null;
    var napi_remove_env_cleanup_hook: ?*const @TypeOf(n.napi_remove_env_cleanup_hook) = null;
    var napi_remove_wrap: ?*const @TypeOf(n.napi_remove_wrap) = null;
    var napi_resolve_deferred: ?*const @TypeOf(n.napi_resolve_deferred) = null;
    var napi_set_element: ?*const @TypeOf(n.napi_set_element) = null;
    var napi_set_instance_data: ?*const @TypeOf(n.napi_set_instance_data) = null;
    var napi_set_named_property: ?*const @TypeOf(n.napi_set_named_property) = null;
    var napi_set_property: ?*const @TypeOf(n.napi_set_property) = null;
    var napi_throw: ?*const @TypeOf(n.napi_throw) = null;
    var napi_throw_error: ?*const @TypeOf(n.napi_throw_error) = null;
    var napi_throw_range_error: ?*const @TypeOf(n.napi_throw_range_error) = null;
    var napi_throw_type_error: ?*const @TypeOf(n.napi_throw_type_error) = null;
    var napi_type_tag_object: ?*const @TypeOf(n.napi_type_tag_object) = null;
    var napi_unref_threadsafe_function: ?*const @TypeOf(n.napi_unref_threadsafe_function) = null;
    var napi_unwrap: ?*const @TypeOf(n.napi_unwrap) = null;
    var napi_wrap: ?*const @TypeOf(n.napi_wrap) = null;
    var node_api_create_buffer_from_arraybuffer: ?*const @TypeOf(n.node_api_create_buffer_from_arraybuffer) = null;
    var node_api_create_external_string_latin1: ?*const @TypeOf(n.node_api_create_external_string_latin1) = null;
    var node_api_create_external_string_utf16: ?*const @TypeOf(n.node_api_create_external_string_utf16) = null;
    var node_api_create_property_key_latin1: ?*const @TypeOf(n.node_api_create_property_key_latin1) = null;
    var node_api_create_property_key_utf16: ?*const @TypeOf(n.node_api_create_property_key_utf16) = null;
    var node_api_create_property_key_utf8: ?*const @TypeOf(n.node_api_create_property_key_utf8) = null;
    var node_api_create_syntax_error: ?*const @TypeOf(n.node_api_create_syntax_error) = null;
    var node_api_symbol_for: ?*const @TypeOf(n.node_api_symbol_for) = null;
    var node_api_throw_syntax_error: ?*const @TypeOf(n.node_api_throw_syntax_error) = null;
    var napi_get_node_version: ?*const @TypeOf(n.napi_get_node_version) = null;
    var napi_get_version: ?*const @TypeOf(n.napi_get_version) = null;
    var napi_get_uv_event_loop: ?*const @TypeOf(n.napi_get_uv_event_loop) = null;
    var napi_run_script: ?*const @TypeOf(n.napi_run_script) = null;
    var napi_strict_equals: ?*const @TypeOf(n.napi_strict_equals) = null;
    var napi_typeof: ?*const @TypeOf(n.napi_typeof) = null;
    var node_api_get_module_file_name: ?*const @TypeOf(n.node_api_get_module_file_name) = null;
};
pub export fn napi_acquire_threadsafe_function(
    arg0: @typeInfo(@TypeOf(n.napi_acquire_threadsafe_function)).@"fn".params[0].type.?,
) @typeInfo(@TypeOf(n.napi_acquire_threadsafe_function)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_acquire_threadsafe_function), "napi_acquire_threadsafe_function", &symbols.napi_acquire_threadsafe_function);
    return ptr(arg0);
}
pub export fn napi_add_async_cleanup_hook(
    arg0: @typeInfo(@TypeOf(n.napi_add_async_cleanup_hook)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_add_async_cleanup_hook)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_add_async_cleanup_hook)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_add_async_cleanup_hook)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_add_async_cleanup_hook)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_add_async_cleanup_hook), "napi_add_async_cleanup_hook", &symbols.napi_add_async_cleanup_hook);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_add_env_cleanup_hook(
    arg0: @typeInfo(@TypeOf(n.napi_add_env_cleanup_hook)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_add_env_cleanup_hook)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_add_env_cleanup_hook)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_add_env_cleanup_hook)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_add_env_cleanup_hook), "napi_add_env_cleanup_hook", &symbols.napi_add_env_cleanup_hook);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_add_finalizer(
    arg0: @typeInfo(@TypeOf(n.napi_add_finalizer)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_add_finalizer)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_add_finalizer)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_add_finalizer)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_add_finalizer)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.napi_add_finalizer)).@"fn".params[5].type.?,
) @typeInfo(@TypeOf(n.napi_add_finalizer)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_add_finalizer), "napi_add_finalizer", &symbols.napi_add_finalizer);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5);
}
pub export fn napi_adjust_external_memory(
    arg0: @typeInfo(@TypeOf(n.napi_adjust_external_memory)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_adjust_external_memory)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_adjust_external_memory)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_adjust_external_memory)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_adjust_external_memory), "napi_adjust_external_memory", &symbols.napi_adjust_external_memory);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_async_destroy(
    arg0: @typeInfo(@TypeOf(n.napi_async_destroy)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_async_destroy)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_async_destroy)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_async_destroy), "napi_async_destroy", &symbols.napi_async_destroy);
    return ptr(arg0, arg1);
}
pub export fn napi_async_init(
    arg0: @typeInfo(@TypeOf(n.napi_async_init)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_async_init)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_async_init)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_async_init)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_async_init)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_async_init), "napi_async_init", &symbols.napi_async_init);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_call_function(
    arg0: @typeInfo(@TypeOf(n.napi_call_function)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_call_function)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_call_function)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_call_function)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_call_function)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.napi_call_function)).@"fn".params[5].type.?,
) @typeInfo(@TypeOf(n.napi_call_function)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_call_function), "napi_call_function", &symbols.napi_call_function);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5);
}
pub export fn napi_call_threadsafe_function(
    arg0: @typeInfo(@TypeOf(n.napi_call_threadsafe_function)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_call_threadsafe_function)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_call_threadsafe_function)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_call_threadsafe_function)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_call_threadsafe_function), "napi_call_threadsafe_function", &symbols.napi_call_threadsafe_function);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_cancel_async_work(
    arg0: @typeInfo(@TypeOf(n.napi_cancel_async_work)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_cancel_async_work)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_cancel_async_work)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_cancel_async_work), "napi_cancel_async_work", &symbols.napi_cancel_async_work);
    return ptr(arg0, arg1);
}
pub export fn napi_check_object_type_tag(
    arg0: @typeInfo(@TypeOf(n.napi_check_object_type_tag)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_check_object_type_tag)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_check_object_type_tag)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_check_object_type_tag)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_check_object_type_tag)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_check_object_type_tag), "napi_check_object_type_tag", &symbols.napi_check_object_type_tag);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_close_callback_scope(
    arg0: @typeInfo(@TypeOf(n.napi_close_callback_scope)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_close_callback_scope)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_close_callback_scope)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_close_callback_scope), "napi_close_callback_scope", &symbols.napi_close_callback_scope);
    return ptr(arg0, arg1);
}
pub export fn napi_close_escapable_handle_scope(
    arg0: @typeInfo(@TypeOf(n.napi_close_escapable_handle_scope)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_close_escapable_handle_scope)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_close_escapable_handle_scope)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_close_escapable_handle_scope), "napi_close_escapable_handle_scope", &symbols.napi_close_escapable_handle_scope);
    return ptr(arg0, arg1);
}
pub export fn napi_close_handle_scope(
    arg0: @typeInfo(@TypeOf(n.napi_close_handle_scope)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_close_handle_scope)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_close_handle_scope)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_close_handle_scope), "napi_close_handle_scope", &symbols.napi_close_handle_scope);
    return ptr(arg0, arg1);
}
pub export fn napi_coerce_to_bool(
    arg0: @typeInfo(@TypeOf(n.napi_coerce_to_bool)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_coerce_to_bool)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_coerce_to_bool)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_coerce_to_bool)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_coerce_to_bool), "napi_coerce_to_bool", &symbols.napi_coerce_to_bool);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_coerce_to_number(
    arg0: @typeInfo(@TypeOf(n.napi_coerce_to_number)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_coerce_to_number)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_coerce_to_number)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_coerce_to_number)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_coerce_to_number), "napi_coerce_to_number", &symbols.napi_coerce_to_number);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_coerce_to_object(
    arg0: @typeInfo(@TypeOf(n.napi_coerce_to_object)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_coerce_to_object)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_coerce_to_object)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_coerce_to_object)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_coerce_to_object), "napi_coerce_to_object", &symbols.napi_coerce_to_object);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_coerce_to_string(
    arg0: @typeInfo(@TypeOf(n.napi_coerce_to_string)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_coerce_to_string)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_coerce_to_string)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_coerce_to_string)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_coerce_to_string), "napi_coerce_to_string", &symbols.napi_coerce_to_string);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_create_array(
    arg0: @typeInfo(@TypeOf(n.napi_create_array)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_array)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_create_array)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_array), "napi_create_array", &symbols.napi_create_array);
    return ptr(arg0, arg1);
}
pub export fn napi_create_array_with_length(
    arg0: @typeInfo(@TypeOf(n.napi_create_array_with_length)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_array_with_length)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_array_with_length)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_create_array_with_length)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_array_with_length), "napi_create_array_with_length", &symbols.napi_create_array_with_length);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_create_arraybuffer(
    arg0: @typeInfo(@TypeOf(n.napi_create_arraybuffer)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_arraybuffer)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_arraybuffer)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_arraybuffer)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_create_arraybuffer)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_arraybuffer), "napi_create_arraybuffer", &symbols.napi_create_arraybuffer);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_create_async_work(
    arg0: @typeInfo(@TypeOf(n.napi_create_async_work)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_async_work)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_async_work)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_async_work)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_create_async_work)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.napi_create_async_work)).@"fn".params[5].type.?,
    arg6: @typeInfo(@TypeOf(n.napi_create_async_work)).@"fn".params[6].type.?,
) @typeInfo(@TypeOf(n.napi_create_async_work)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_async_work), "napi_create_async_work", &symbols.napi_create_async_work);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
}
pub export fn napi_create_bigint_int64(
    arg0: @typeInfo(@TypeOf(n.napi_create_bigint_int64)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_bigint_int64)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_bigint_int64)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_create_bigint_int64)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_bigint_int64), "napi_create_bigint_int64", &symbols.napi_create_bigint_int64);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_create_bigint_uint64(
    arg0: @typeInfo(@TypeOf(n.napi_create_bigint_uint64)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_bigint_uint64)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_bigint_uint64)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_create_bigint_uint64)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_bigint_uint64), "napi_create_bigint_uint64", &symbols.napi_create_bigint_uint64);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_create_bigint_words(
    arg0: @typeInfo(@TypeOf(n.napi_create_bigint_words)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_bigint_words)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_bigint_words)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_bigint_words)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_create_bigint_words)).@"fn".params[4].type.?,
) @typeInfo(@TypeOf(n.napi_create_bigint_words)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_bigint_words), "napi_create_bigint_words", &symbols.napi_create_bigint_words);
    return ptr(arg0, arg1, arg2, arg3, arg4);
}
pub export fn napi_create_buffer(
    arg0: @typeInfo(@TypeOf(n.napi_create_buffer)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_buffer)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_buffer)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_buffer)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_create_buffer)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_buffer), "napi_create_buffer", &symbols.napi_create_buffer);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_create_buffer_copy(
    arg0: @typeInfo(@TypeOf(n.napi_create_buffer_copy)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_buffer_copy)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_buffer_copy)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_buffer_copy)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_create_buffer_copy)).@"fn".params[4].type.?,
) @typeInfo(@TypeOf(n.napi_create_buffer_copy)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_buffer_copy), "napi_create_buffer_copy", &symbols.napi_create_buffer_copy);
    return ptr(arg0, arg1, arg2, arg3, arg4);
}
pub export fn napi_create_dataview(
    arg0: @typeInfo(@TypeOf(n.napi_create_dataview)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_dataview)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_dataview)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_dataview)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_create_dataview)).@"fn".params[4].type.?,
) @typeInfo(@TypeOf(n.napi_create_dataview)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_dataview), "napi_create_dataview", &symbols.napi_create_dataview);
    return ptr(arg0, arg1, arg2, arg3, arg4);
}
pub export fn napi_create_date(
    arg0: @typeInfo(@TypeOf(n.napi_create_date)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_date)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_date)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_create_date)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_date), "napi_create_date", &symbols.napi_create_date);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_create_double(
    arg0: @typeInfo(@TypeOf(n.napi_create_double)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_double)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_double)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_create_double)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_double), "napi_create_double", &symbols.napi_create_double);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_create_error(
    arg0: @typeInfo(@TypeOf(n.napi_create_error)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_error)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_error)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_error)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_create_error)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_error), "napi_create_error", &symbols.napi_create_error);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_create_external(
    arg0: @typeInfo(@TypeOf(n.napi_create_external)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_external)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_external)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_external)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_create_external)).@"fn".params[4].type.?,
) @typeInfo(@TypeOf(n.napi_create_external)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_external), "napi_create_external", &symbols.napi_create_external);
    return ptr(arg0, arg1, arg2, arg3, arg4);
}
pub export fn napi_create_external_arraybuffer(
    arg0: @typeInfo(@TypeOf(n.napi_create_external_arraybuffer)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_external_arraybuffer)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_external_arraybuffer)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_external_arraybuffer)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_create_external_arraybuffer)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.napi_create_external_arraybuffer)).@"fn".params[5].type.?,
) @typeInfo(@TypeOf(n.napi_create_external_arraybuffer)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_external_arraybuffer), "napi_create_external_arraybuffer", &symbols.napi_create_external_arraybuffer);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5);
}
pub export fn napi_create_external_buffer(
    arg0: @typeInfo(@TypeOf(n.napi_create_external_buffer)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_external_buffer)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_external_buffer)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_external_buffer)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_create_external_buffer)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.napi_create_external_buffer)).@"fn".params[5].type.?,
) @typeInfo(@TypeOf(n.napi_create_external_buffer)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_external_buffer), "napi_create_external_buffer", &symbols.napi_create_external_buffer);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5);
}
pub export fn napi_create_function(
    arg0: @typeInfo(@TypeOf(n.napi_create_function)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_function)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_function)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_function)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_create_function)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.napi_create_function)).@"fn".params[5].type.?,
) @typeInfo(@TypeOf(n.napi_create_function)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_function), "napi_create_function", &symbols.napi_create_function);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5);
}
pub export fn napi_create_int32(
    arg0: @typeInfo(@TypeOf(n.napi_create_int32)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_int32)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_int32)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_create_int32)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_int32), "napi_create_int32", &symbols.napi_create_int32);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_create_int64(
    arg0: @typeInfo(@TypeOf(n.napi_create_int64)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_int64)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_int64)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_create_int64)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_int64), "napi_create_int64", &symbols.napi_create_int64);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_create_object(
    arg0: @typeInfo(@TypeOf(n.napi_create_object)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_object)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_create_object)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_object), "napi_create_object", &symbols.napi_create_object);
    return ptr(arg0, arg1);
}
pub export fn napi_create_promise(
    arg0: @typeInfo(@TypeOf(n.napi_create_promise)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_promise)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_promise)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_create_promise)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_promise), "napi_create_promise", &symbols.napi_create_promise);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_create_range_error(
    arg0: @typeInfo(@TypeOf(n.napi_create_range_error)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_range_error)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_range_error)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_range_error)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_create_range_error)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_range_error), "napi_create_range_error", &symbols.napi_create_range_error);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_create_reference(
    arg0: @typeInfo(@TypeOf(n.napi_create_reference)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_reference)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_reference)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_reference)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_create_reference)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_reference), "napi_create_reference", &symbols.napi_create_reference);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_create_string_latin1(
    arg0: @typeInfo(@TypeOf(n.napi_create_string_latin1)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_string_latin1)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_string_latin1)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_string_latin1)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_create_string_latin1)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_string_latin1), "napi_create_string_latin1", &symbols.napi_create_string_latin1);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_create_string_utf16(
    arg0: @typeInfo(@TypeOf(n.napi_create_string_utf16)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_string_utf16)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_string_utf16)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_string_utf16)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_create_string_utf16)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_string_utf16), "napi_create_string_utf16", &symbols.napi_create_string_utf16);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_create_string_utf8(
    arg0: @typeInfo(@TypeOf(n.napi_create_string_utf8)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_string_utf8)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_string_utf8)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_string_utf8)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_create_string_utf8)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_string_utf8), "napi_create_string_utf8", &symbols.napi_create_string_utf8);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_create_symbol(
    arg0: @typeInfo(@TypeOf(n.napi_create_symbol)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_symbol)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_symbol)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_create_symbol)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_symbol), "napi_create_symbol", &symbols.napi_create_symbol);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_create_threadsafe_function(
    arg0: @typeInfo(@TypeOf(n.napi_create_threadsafe_function)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_threadsafe_function)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_threadsafe_function)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_threadsafe_function)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_create_threadsafe_function)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.napi_create_threadsafe_function)).@"fn".params[5].type.?,
    arg6: @typeInfo(@TypeOf(n.napi_create_threadsafe_function)).@"fn".params[6].type.?,
    arg7: @typeInfo(@TypeOf(n.napi_create_threadsafe_function)).@"fn".params[7].type.?,
    arg8: @typeInfo(@TypeOf(n.napi_create_threadsafe_function)).@"fn".params[8].type.?,
    arg9: @typeInfo(@TypeOf(n.napi_create_threadsafe_function)).@"fn".params[9].type.?,
    arg10: @typeInfo(@TypeOf(n.napi_create_threadsafe_function)).@"fn".params[10].type.?,
) @typeInfo(@TypeOf(n.napi_create_threadsafe_function)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_threadsafe_function), "napi_create_threadsafe_function", &symbols.napi_create_threadsafe_function);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}
pub export fn napi_create_type_error(
    arg0: @typeInfo(@TypeOf(n.napi_create_type_error)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_type_error)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_type_error)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_type_error)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_create_type_error)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_type_error), "napi_create_type_error", &symbols.napi_create_type_error);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_create_typedarray(
    arg0: @typeInfo(@TypeOf(n.napi_create_typedarray)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_typedarray)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_typedarray)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_create_typedarray)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_create_typedarray)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.napi_create_typedarray)).@"fn".params[5].type.?,
) @typeInfo(@TypeOf(n.napi_create_typedarray)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_typedarray), "napi_create_typedarray", &symbols.napi_create_typedarray);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5);
}
pub export fn napi_create_uint32(
    arg0: @typeInfo(@TypeOf(n.napi_create_uint32)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_create_uint32)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_create_uint32)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_create_uint32)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_create_uint32), "napi_create_uint32", &symbols.napi_create_uint32);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_define_class(
    arg0: @typeInfo(@TypeOf(n.napi_define_class)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_define_class)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_define_class)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_define_class)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_define_class)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.napi_define_class)).@"fn".params[5].type.?,
    arg6: @typeInfo(@TypeOf(n.napi_define_class)).@"fn".params[6].type.?,
    arg7: @typeInfo(@TypeOf(n.napi_define_class)).@"fn".params[7].type.?,
) @typeInfo(@TypeOf(n.napi_define_class)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_define_class), "napi_define_class", &symbols.napi_define_class);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
pub export fn napi_define_properties(
    arg0: @typeInfo(@TypeOf(n.napi_define_properties)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_define_properties)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_define_properties)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_define_properties)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_define_properties)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_define_properties), "napi_define_properties", &symbols.napi_define_properties);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_delete_async_work(
    arg0: @typeInfo(@TypeOf(n.napi_delete_async_work)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_delete_async_work)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_delete_async_work)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_delete_async_work), "napi_delete_async_work", &symbols.napi_delete_async_work);
    return ptr(arg0, arg1);
}
pub export fn napi_delete_element(
    arg0: @typeInfo(@TypeOf(n.napi_delete_element)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_delete_element)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_delete_element)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_delete_element)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_delete_element)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_delete_element), "napi_delete_element", &symbols.napi_delete_element);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_delete_property(
    arg0: @typeInfo(@TypeOf(n.napi_delete_property)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_delete_property)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_delete_property)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_delete_property)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_delete_property)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_delete_property), "napi_delete_property", &symbols.napi_delete_property);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_delete_reference(
    arg0: @typeInfo(@TypeOf(n.napi_delete_reference)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_delete_reference)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_delete_reference)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_delete_reference), "napi_delete_reference", &symbols.napi_delete_reference);
    return ptr(arg0, arg1);
}
pub export fn napi_detach_arraybuffer(
    arg0: @typeInfo(@TypeOf(n.napi_detach_arraybuffer)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_detach_arraybuffer)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_detach_arraybuffer)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_detach_arraybuffer), "napi_detach_arraybuffer", &symbols.napi_detach_arraybuffer);
    return ptr(arg0, arg1);
}
pub export fn napi_escape_handle(
    arg0: @typeInfo(@TypeOf(n.napi_escape_handle)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_escape_handle)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_escape_handle)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_escape_handle)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_escape_handle)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_escape_handle), "napi_escape_handle", &symbols.napi_escape_handle);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_fatal_error(
    arg0: @typeInfo(@TypeOf(n.napi_fatal_error)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_fatal_error)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_fatal_error)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_fatal_error)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_fatal_error)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_fatal_error), "napi_fatal_error", &symbols.napi_fatal_error);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_fatal_exception(
    arg0: @typeInfo(@TypeOf(n.napi_fatal_exception)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_fatal_exception)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_fatal_exception)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_fatal_exception), "napi_fatal_exception", &symbols.napi_fatal_exception);
    return ptr(arg0, arg1);
}
pub export fn napi_get_all_property_names(
    arg0: @typeInfo(@TypeOf(n.napi_get_all_property_names)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_all_property_names)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_all_property_names)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_get_all_property_names)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_get_all_property_names)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.napi_get_all_property_names)).@"fn".params[5].type.?,
) @typeInfo(@TypeOf(n.napi_get_all_property_names)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_all_property_names), "napi_get_all_property_names", &symbols.napi_get_all_property_names);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5);
}
pub export fn napi_get_and_clear_last_exception(
    arg0: @typeInfo(@TypeOf(n.napi_get_and_clear_last_exception)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_and_clear_last_exception)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_get_and_clear_last_exception)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_and_clear_last_exception), "napi_get_and_clear_last_exception", &symbols.napi_get_and_clear_last_exception);
    return ptr(arg0, arg1);
}
pub export fn napi_get_array_length(
    arg0: @typeInfo(@TypeOf(n.napi_get_array_length)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_array_length)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_array_length)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_get_array_length)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_array_length), "napi_get_array_length", &symbols.napi_get_array_length);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_get_arraybuffer_info(
    arg0: @typeInfo(@TypeOf(n.napi_get_arraybuffer_info)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_arraybuffer_info)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_arraybuffer_info)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_get_arraybuffer_info)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_get_arraybuffer_info)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_arraybuffer_info), "napi_get_arraybuffer_info", &symbols.napi_get_arraybuffer_info);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_get_boolean(
    arg0: @typeInfo(@TypeOf(n.napi_get_boolean)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_boolean)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_boolean)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_get_boolean)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_boolean), "napi_get_boolean", &symbols.napi_get_boolean);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_get_buffer_info(
    arg0: @typeInfo(@TypeOf(n.napi_get_buffer_info)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_buffer_info)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_buffer_info)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_get_buffer_info)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_get_buffer_info)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_buffer_info), "napi_get_buffer_info", &symbols.napi_get_buffer_info);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_get_cb_info(
    arg0: @typeInfo(@TypeOf(n.napi_get_cb_info)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_cb_info)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_cb_info)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_get_cb_info)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_get_cb_info)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.napi_get_cb_info)).@"fn".params[5].type.?,
) @typeInfo(@TypeOf(n.napi_get_cb_info)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_cb_info), "napi_get_cb_info", &symbols.napi_get_cb_info);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5);
}
pub export fn napi_get_dataview_info(
    arg0: @typeInfo(@TypeOf(n.napi_get_dataview_info)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_dataview_info)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_dataview_info)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_get_dataview_info)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_get_dataview_info)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.napi_get_dataview_info)).@"fn".params[5].type.?,
) @typeInfo(@TypeOf(n.napi_get_dataview_info)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_dataview_info), "napi_get_dataview_info", &symbols.napi_get_dataview_info);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5);
}
pub export fn napi_get_date_value(
    arg0: @typeInfo(@TypeOf(n.napi_get_date_value)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_date_value)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_date_value)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_get_date_value)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_date_value), "napi_get_date_value", &symbols.napi_get_date_value);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_get_element(
    arg0: @typeInfo(@TypeOf(n.napi_get_element)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_element)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_element)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_get_element)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_get_element)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_element), "napi_get_element", &symbols.napi_get_element);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_get_global(
    arg0: @typeInfo(@TypeOf(n.napi_get_global)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_global)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_get_global)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_global), "napi_get_global", &symbols.napi_get_global);
    return ptr(arg0, arg1);
}
pub export fn napi_get_instance_data(
    arg0: @typeInfo(@TypeOf(n.napi_get_instance_data)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_instance_data)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_get_instance_data)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_instance_data), "napi_get_instance_data", &symbols.napi_get_instance_data);
    return ptr(arg0, arg1);
}
pub export fn napi_get_last_error_info(
    arg0: @typeInfo(@TypeOf(n.napi_get_last_error_info)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_last_error_info)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_get_last_error_info)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_last_error_info), "napi_get_last_error_info", &symbols.napi_get_last_error_info);
    return ptr(arg0, arg1);
}
pub export fn napi_get_named_property(
    arg0: @typeInfo(@TypeOf(n.napi_get_named_property)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_named_property)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_named_property)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_get_named_property)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_get_named_property)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_named_property), "napi_get_named_property", &symbols.napi_get_named_property);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_get_new_target(
    arg0: @typeInfo(@TypeOf(n.napi_get_new_target)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_new_target)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_new_target)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_get_new_target)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_new_target), "napi_get_new_target", &symbols.napi_get_new_target);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_get_null(
    arg0: @typeInfo(@TypeOf(n.napi_get_null)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_null)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_get_null)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_null), "napi_get_null", &symbols.napi_get_null);
    return ptr(arg0, arg1);
}
pub export fn napi_get_property(
    arg0: @typeInfo(@TypeOf(n.napi_get_property)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_property)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_property)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_get_property)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_get_property)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_property), "napi_get_property", &symbols.napi_get_property);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_get_property_names(
    arg0: @typeInfo(@TypeOf(n.napi_get_property_names)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_property_names)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_property_names)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_get_property_names)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_property_names), "napi_get_property_names", &symbols.napi_get_property_names);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_get_prototype(
    arg0: @typeInfo(@TypeOf(n.napi_get_prototype)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_prototype)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_prototype)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_get_prototype)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_prototype), "napi_get_prototype", &symbols.napi_get_prototype);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_get_reference_value(
    arg0: @typeInfo(@TypeOf(n.napi_get_reference_value)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_reference_value)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_reference_value)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_get_reference_value)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_reference_value), "napi_get_reference_value", &symbols.napi_get_reference_value);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_get_threadsafe_function_context(
    arg0: @typeInfo(@TypeOf(n.napi_get_threadsafe_function_context)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_threadsafe_function_context)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_get_threadsafe_function_context)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_threadsafe_function_context), "napi_get_threadsafe_function_context", &symbols.napi_get_threadsafe_function_context);
    return ptr(arg0, arg1);
}
pub export fn napi_get_typedarray_info(
    arg0: @typeInfo(@TypeOf(n.napi_get_typedarray_info)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_typedarray_info)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_typedarray_info)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_get_typedarray_info)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_get_typedarray_info)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.napi_get_typedarray_info)).@"fn".params[5].type.?,
    arg6: @typeInfo(@TypeOf(n.napi_get_typedarray_info)).@"fn".params[6].type.?,
) @typeInfo(@TypeOf(n.napi_get_typedarray_info)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_typedarray_info), "napi_get_typedarray_info", &symbols.napi_get_typedarray_info);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
}
pub export fn napi_get_undefined(
    arg0: @typeInfo(@TypeOf(n.napi_get_undefined)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_undefined)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_get_undefined)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_undefined), "napi_get_undefined", &symbols.napi_get_undefined);
    return ptr(arg0, arg1);
}
pub export fn napi_get_value_bigint_int64(
    arg0: @typeInfo(@TypeOf(n.napi_get_value_bigint_int64)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_value_bigint_int64)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_value_bigint_int64)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_get_value_bigint_int64)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_get_value_bigint_int64)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_value_bigint_int64), "napi_get_value_bigint_int64", &symbols.napi_get_value_bigint_int64);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_get_value_bigint_uint64(
    arg0: @typeInfo(@TypeOf(n.napi_get_value_bigint_uint64)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_value_bigint_uint64)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_value_bigint_uint64)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_get_value_bigint_uint64)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_get_value_bigint_uint64)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_value_bigint_uint64), "napi_get_value_bigint_uint64", &symbols.napi_get_value_bigint_uint64);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_get_value_bigint_words(
    arg0: @typeInfo(@TypeOf(n.napi_get_value_bigint_words)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_value_bigint_words)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_value_bigint_words)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_get_value_bigint_words)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_get_value_bigint_words)).@"fn".params[4].type.?,
) @typeInfo(@TypeOf(n.napi_get_value_bigint_words)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_value_bigint_words), "napi_get_value_bigint_words", &symbols.napi_get_value_bigint_words);
    return ptr(arg0, arg1, arg2, arg3, arg4);
}
pub export fn napi_get_value_bool(
    arg0: @typeInfo(@TypeOf(n.napi_get_value_bool)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_value_bool)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_value_bool)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_get_value_bool)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_value_bool), "napi_get_value_bool", &symbols.napi_get_value_bool);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_get_value_double(
    arg0: @typeInfo(@TypeOf(n.napi_get_value_double)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_value_double)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_value_double)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_get_value_double)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_value_double), "napi_get_value_double", &symbols.napi_get_value_double);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_get_value_external(
    arg0: @typeInfo(@TypeOf(n.napi_get_value_external)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_value_external)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_value_external)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_get_value_external)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_value_external), "napi_get_value_external", &symbols.napi_get_value_external);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_get_value_int32(
    arg0: @typeInfo(@TypeOf(n.napi_get_value_int32)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_value_int32)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_value_int32)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_get_value_int32)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_value_int32), "napi_get_value_int32", &symbols.napi_get_value_int32);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_get_value_int64(
    arg0: @typeInfo(@TypeOf(n.napi_get_value_int64)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_value_int64)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_value_int64)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_get_value_int64)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_value_int64), "napi_get_value_int64", &symbols.napi_get_value_int64);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_get_value_string_latin1(
    arg0: @typeInfo(@TypeOf(n.napi_get_value_string_latin1)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_value_string_latin1)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_value_string_latin1)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_get_value_string_latin1)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_get_value_string_latin1)).@"fn".params[4].type.?,
) @typeInfo(@TypeOf(n.napi_get_value_string_latin1)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_value_string_latin1), "napi_get_value_string_latin1", &symbols.napi_get_value_string_latin1);
    return ptr(arg0, arg1, arg2, arg3, arg4);
}
pub export fn napi_get_value_string_utf16(
    arg0: @typeInfo(@TypeOf(n.napi_get_value_string_utf16)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_value_string_utf16)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_value_string_utf16)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_get_value_string_utf16)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_get_value_string_utf16)).@"fn".params[4].type.?,
) @typeInfo(@TypeOf(n.napi_get_value_string_utf16)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_value_string_utf16), "napi_get_value_string_utf16", &symbols.napi_get_value_string_utf16);
    return ptr(arg0, arg1, arg2, arg3, arg4);
}
pub export fn napi_get_value_string_utf8(
    arg0: @typeInfo(@TypeOf(n.napi_get_value_string_utf8)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_value_string_utf8)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_value_string_utf8)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_get_value_string_utf8)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_get_value_string_utf8)).@"fn".params[4].type.?,
) @typeInfo(@TypeOf(n.napi_get_value_string_utf8)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_value_string_utf8), "napi_get_value_string_utf8", &symbols.napi_get_value_string_utf8);
    return ptr(arg0, arg1, arg2, arg3, arg4);
}
pub export fn napi_get_value_uint32(
    arg0: @typeInfo(@TypeOf(n.napi_get_value_uint32)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_value_uint32)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_get_value_uint32)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_get_value_uint32)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_value_uint32), "napi_get_value_uint32", &symbols.napi_get_value_uint32);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_has_element(
    arg0: @typeInfo(@TypeOf(n.napi_has_element)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_has_element)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_has_element)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_has_element)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_has_element)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_has_element), "napi_has_element", &symbols.napi_has_element);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_has_named_property(
    arg0: @typeInfo(@TypeOf(n.napi_has_named_property)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_has_named_property)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_has_named_property)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_has_named_property)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_has_named_property)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_has_named_property), "napi_has_named_property", &symbols.napi_has_named_property);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_has_own_property(
    arg0: @typeInfo(@TypeOf(n.napi_has_own_property)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_has_own_property)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_has_own_property)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_has_own_property)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_has_own_property)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_has_own_property), "napi_has_own_property", &symbols.napi_has_own_property);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_has_property(
    arg0: @typeInfo(@TypeOf(n.napi_has_property)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_has_property)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_has_property)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_has_property)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_has_property)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_has_property), "napi_has_property", &symbols.napi_has_property);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_instanceof(
    arg0: @typeInfo(@TypeOf(n.napi_instanceof)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_instanceof)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_instanceof)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_instanceof)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_instanceof)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_instanceof), "napi_instanceof", &symbols.napi_instanceof);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_is_array(
    arg0: @typeInfo(@TypeOf(n.napi_is_array)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_is_array)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_is_array)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_is_array)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_is_array), "napi_is_array", &symbols.napi_is_array);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_is_arraybuffer(
    arg0: @typeInfo(@TypeOf(n.napi_is_arraybuffer)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_is_arraybuffer)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_is_arraybuffer)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_is_arraybuffer)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_is_arraybuffer), "napi_is_arraybuffer", &symbols.napi_is_arraybuffer);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_is_buffer(
    arg0: @typeInfo(@TypeOf(n.napi_is_buffer)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_is_buffer)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_is_buffer)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_is_buffer)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_is_buffer), "napi_is_buffer", &symbols.napi_is_buffer);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_is_dataview(
    arg0: @typeInfo(@TypeOf(n.napi_is_dataview)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_is_dataview)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_is_dataview)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_is_dataview)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_is_dataview), "napi_is_dataview", &symbols.napi_is_dataview);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_is_date(
    arg0: @typeInfo(@TypeOf(n.napi_is_date)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_is_date)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_is_date)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_is_date)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_is_date), "napi_is_date", &symbols.napi_is_date);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_is_detached_arraybuffer(
    arg0: @typeInfo(@TypeOf(n.napi_is_detached_arraybuffer)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_is_detached_arraybuffer)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_is_detached_arraybuffer)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_is_detached_arraybuffer)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_is_detached_arraybuffer), "napi_is_detached_arraybuffer", &symbols.napi_is_detached_arraybuffer);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_is_error(
    arg0: @typeInfo(@TypeOf(n.napi_is_error)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_is_error)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_is_error)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_is_error)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_is_error), "napi_is_error", &symbols.napi_is_error);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_is_exception_pending(
    arg0: @typeInfo(@TypeOf(n.napi_is_exception_pending)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_is_exception_pending)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_is_exception_pending)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_is_exception_pending), "napi_is_exception_pending", &symbols.napi_is_exception_pending);
    return ptr(arg0, arg1);
}
pub export fn napi_is_promise(
    arg0: @typeInfo(@TypeOf(n.napi_is_promise)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_is_promise)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_is_promise)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_is_promise)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_is_promise), "napi_is_promise", &symbols.napi_is_promise);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_is_typedarray(
    arg0: @typeInfo(@TypeOf(n.napi_is_typedarray)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_is_typedarray)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_is_typedarray)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_is_typedarray)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_is_typedarray), "napi_is_typedarray", &symbols.napi_is_typedarray);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_make_callback(
    arg0: @typeInfo(@TypeOf(n.napi_make_callback)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_make_callback)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_make_callback)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_make_callback)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_make_callback)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.napi_make_callback)).@"fn".params[5].type.?,
    arg6: @typeInfo(@TypeOf(n.napi_make_callback)).@"fn".params[6].type.?,
) @typeInfo(@TypeOf(n.napi_make_callback)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_make_callback), "napi_make_callback", &symbols.napi_make_callback);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
}
pub export fn napi_new_instance(
    arg0: @typeInfo(@TypeOf(n.napi_new_instance)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_new_instance)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_new_instance)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_new_instance)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_new_instance)).@"fn".params[4].type.?,
) @typeInfo(@TypeOf(n.napi_new_instance)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_new_instance), "napi_new_instance", &symbols.napi_new_instance);
    return ptr(arg0, arg1, arg2, arg3, arg4);
}
pub export fn napi_object_freeze(
    arg0: @typeInfo(@TypeOf(n.napi_object_freeze)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_object_freeze)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_object_freeze)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_object_freeze), "napi_object_freeze", &symbols.napi_object_freeze);
    return ptr(arg0, arg1);
}
pub export fn napi_object_seal(
    arg0: @typeInfo(@TypeOf(n.napi_object_seal)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_object_seal)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_object_seal)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_object_seal), "napi_object_seal", &symbols.napi_object_seal);
    return ptr(arg0, arg1);
}
pub export fn napi_open_callback_scope(
    arg0: @typeInfo(@TypeOf(n.napi_open_callback_scope)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_open_callback_scope)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_open_callback_scope)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_open_callback_scope)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_open_callback_scope)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_open_callback_scope), "napi_open_callback_scope", &symbols.napi_open_callback_scope);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_open_escapable_handle_scope(
    arg0: @typeInfo(@TypeOf(n.napi_open_escapable_handle_scope)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_open_escapable_handle_scope)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_open_escapable_handle_scope)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_open_escapable_handle_scope), "napi_open_escapable_handle_scope", &symbols.napi_open_escapable_handle_scope);
    return ptr(arg0, arg1);
}
pub export fn napi_open_handle_scope(
    arg0: @typeInfo(@TypeOf(n.napi_open_handle_scope)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_open_handle_scope)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_open_handle_scope)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_open_handle_scope), "napi_open_handle_scope", &symbols.napi_open_handle_scope);
    return ptr(arg0, arg1);
}
pub export fn napi_queue_async_work(
    arg0: @typeInfo(@TypeOf(n.napi_queue_async_work)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_queue_async_work)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_queue_async_work)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_queue_async_work), "napi_queue_async_work", &symbols.napi_queue_async_work);
    return ptr(arg0, arg1);
}
pub export fn napi_ref_threadsafe_function(
    arg0: @typeInfo(@TypeOf(n.napi_ref_threadsafe_function)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_ref_threadsafe_function)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_ref_threadsafe_function)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_ref_threadsafe_function), "napi_ref_threadsafe_function", &symbols.napi_ref_threadsafe_function);
    return ptr(arg0, arg1);
}
pub export fn napi_reference_ref(
    arg0: @typeInfo(@TypeOf(n.napi_reference_ref)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_reference_ref)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_reference_ref)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_reference_ref)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_reference_ref), "napi_reference_ref", &symbols.napi_reference_ref);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_reference_unref(
    arg0: @typeInfo(@TypeOf(n.napi_reference_unref)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_reference_unref)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_reference_unref)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_reference_unref)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_reference_unref), "napi_reference_unref", &symbols.napi_reference_unref);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_reject_deferred(
    arg0: @typeInfo(@TypeOf(n.napi_reject_deferred)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_reject_deferred)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_reject_deferred)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_reject_deferred)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_reject_deferred), "napi_reject_deferred", &symbols.napi_reject_deferred);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_release_threadsafe_function(
    arg0: @typeInfo(@TypeOf(n.napi_release_threadsafe_function)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_release_threadsafe_function)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_release_threadsafe_function)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_release_threadsafe_function), "napi_release_threadsafe_function", &symbols.napi_release_threadsafe_function);
    return ptr(arg0, arg1);
}
pub export fn napi_remove_async_cleanup_hook(
    arg0: @typeInfo(@TypeOf(n.napi_remove_async_cleanup_hook)).@"fn".params[0].type.?,
) @typeInfo(@TypeOf(n.napi_remove_async_cleanup_hook)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_remove_async_cleanup_hook), "napi_remove_async_cleanup_hook", &symbols.napi_remove_async_cleanup_hook);
    return ptr(arg0);
}
pub export fn napi_remove_env_cleanup_hook(
    arg0: @typeInfo(@TypeOf(n.napi_remove_env_cleanup_hook)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_remove_env_cleanup_hook)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_remove_env_cleanup_hook)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_remove_env_cleanup_hook)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_remove_env_cleanup_hook), "napi_remove_env_cleanup_hook", &symbols.napi_remove_env_cleanup_hook);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_remove_wrap(
    arg0: @typeInfo(@TypeOf(n.napi_remove_wrap)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_remove_wrap)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_remove_wrap)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_remove_wrap)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_remove_wrap), "napi_remove_wrap", &symbols.napi_remove_wrap);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_resolve_deferred(
    arg0: @typeInfo(@TypeOf(n.napi_resolve_deferred)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_resolve_deferred)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_resolve_deferred)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_resolve_deferred)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_resolve_deferred), "napi_resolve_deferred", &symbols.napi_resolve_deferred);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_set_element(
    arg0: @typeInfo(@TypeOf(n.napi_set_element)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_set_element)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_set_element)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_set_element)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_set_element)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_set_element), "napi_set_element", &symbols.napi_set_element);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_set_instance_data(
    arg0: @typeInfo(@TypeOf(n.napi_set_instance_data)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_set_instance_data)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_set_instance_data)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_set_instance_data)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_set_instance_data)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_set_instance_data), "napi_set_instance_data", &symbols.napi_set_instance_data);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_set_named_property(
    arg0: @typeInfo(@TypeOf(n.napi_set_named_property)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_set_named_property)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_set_named_property)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_set_named_property)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_set_named_property)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_set_named_property), "napi_set_named_property", &symbols.napi_set_named_property);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_set_property(
    arg0: @typeInfo(@TypeOf(n.napi_set_property)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_set_property)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_set_property)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_set_property)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_set_property)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_set_property), "napi_set_property", &symbols.napi_set_property);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_throw(
    arg0: @typeInfo(@TypeOf(n.napi_throw)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_throw)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_throw)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_throw), "napi_throw", &symbols.napi_throw);
    return ptr(arg0, arg1);
}
pub export fn napi_throw_error(
    arg0: @typeInfo(@TypeOf(n.napi_throw_error)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_throw_error)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_throw_error)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_throw_error)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_throw_error), "napi_throw_error", &symbols.napi_throw_error);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_throw_range_error(
    arg0: @typeInfo(@TypeOf(n.napi_throw_range_error)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_throw_range_error)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_throw_range_error)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_throw_range_error)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_throw_range_error), "napi_throw_range_error", &symbols.napi_throw_range_error);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_throw_type_error(
    arg0: @typeInfo(@TypeOf(n.napi_throw_type_error)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_throw_type_error)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_throw_type_error)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_throw_type_error)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_throw_type_error), "napi_throw_type_error", &symbols.napi_throw_type_error);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_type_tag_object(
    arg0: @typeInfo(@TypeOf(n.napi_type_tag_object)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_type_tag_object)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_type_tag_object)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_type_tag_object)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_type_tag_object), "napi_type_tag_object", &symbols.napi_type_tag_object);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_unref_threadsafe_function(
    arg0: @typeInfo(@TypeOf(n.napi_unref_threadsafe_function)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_unref_threadsafe_function)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_unref_threadsafe_function)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_unref_threadsafe_function), "napi_unref_threadsafe_function", &symbols.napi_unref_threadsafe_function);
    return ptr(arg0, arg1);
}
pub export fn napi_unwrap(
    arg0: @typeInfo(@TypeOf(n.napi_unwrap)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_unwrap)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_unwrap)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_unwrap)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_unwrap), "napi_unwrap", &symbols.napi_unwrap);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_wrap(
    arg0: @typeInfo(@TypeOf(n.napi_wrap)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_wrap)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_wrap)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_wrap)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.napi_wrap)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.napi_wrap)).@"fn".params[5].type.?,
) @typeInfo(@TypeOf(n.napi_wrap)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_wrap), "napi_wrap", &symbols.napi_wrap);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5);
}
pub export fn node_api_create_buffer_from_arraybuffer(
    arg0: @typeInfo(@TypeOf(n.node_api_create_buffer_from_arraybuffer)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.node_api_create_buffer_from_arraybuffer)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.node_api_create_buffer_from_arraybuffer)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.node_api_create_buffer_from_arraybuffer)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.node_api_create_buffer_from_arraybuffer)).@"fn".params[4].type.?,
) @typeInfo(@TypeOf(n.node_api_create_buffer_from_arraybuffer)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.node_api_create_buffer_from_arraybuffer), "node_api_create_buffer_from_arraybuffer", &symbols.node_api_create_buffer_from_arraybuffer);
    return ptr(arg0, arg1, arg2, arg3, arg4);
}
pub export fn node_api_create_external_string_latin1(
    arg0: @typeInfo(@TypeOf(n.node_api_create_external_string_latin1)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.node_api_create_external_string_latin1)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.node_api_create_external_string_latin1)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.node_api_create_external_string_latin1)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.node_api_create_external_string_latin1)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.node_api_create_external_string_latin1)).@"fn".params[5].type.?,
    arg6: @typeInfo(@TypeOf(n.node_api_create_external_string_latin1)).@"fn".params[6].type.?,
) @typeInfo(@TypeOf(n.node_api_create_external_string_latin1)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.node_api_create_external_string_latin1), "node_api_create_external_string_latin1", &symbols.node_api_create_external_string_latin1);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
}
pub export fn node_api_create_external_string_utf16(
    arg0: @typeInfo(@TypeOf(n.node_api_create_external_string_utf16)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.node_api_create_external_string_utf16)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.node_api_create_external_string_utf16)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.node_api_create_external_string_utf16)).@"fn".params[3].type.?,
    arg4: @typeInfo(@TypeOf(n.node_api_create_external_string_utf16)).@"fn".params[4].type.?,
    arg5: @typeInfo(@TypeOf(n.node_api_create_external_string_utf16)).@"fn".params[5].type.?,
    arg6: @typeInfo(@TypeOf(n.node_api_create_external_string_utf16)).@"fn".params[6].type.?,
) @typeInfo(@TypeOf(n.node_api_create_external_string_utf16)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.node_api_create_external_string_utf16), "node_api_create_external_string_utf16", &symbols.node_api_create_external_string_utf16);
    return ptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
}
pub export fn node_api_create_property_key_latin1(
    arg0: @typeInfo(@TypeOf(n.node_api_create_property_key_latin1)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.node_api_create_property_key_latin1)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.node_api_create_property_key_latin1)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.node_api_create_property_key_latin1)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.node_api_create_property_key_latin1)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.node_api_create_property_key_latin1), "node_api_create_property_key_latin1", &symbols.node_api_create_property_key_latin1);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn node_api_create_property_key_utf16(
    arg0: @typeInfo(@TypeOf(n.node_api_create_property_key_utf16)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.node_api_create_property_key_utf16)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.node_api_create_property_key_utf16)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.node_api_create_property_key_utf16)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.node_api_create_property_key_utf16)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.node_api_create_property_key_utf16), "node_api_create_property_key_utf16", &symbols.node_api_create_property_key_utf16);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn node_api_create_property_key_utf8(
    arg0: @typeInfo(@TypeOf(n.node_api_create_property_key_utf8)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.node_api_create_property_key_utf8)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.node_api_create_property_key_utf8)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.node_api_create_property_key_utf8)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.node_api_create_property_key_utf8)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.node_api_create_property_key_utf8), "node_api_create_property_key_utf8", &symbols.node_api_create_property_key_utf8);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn node_api_create_syntax_error(
    arg0: @typeInfo(@TypeOf(n.node_api_create_syntax_error)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.node_api_create_syntax_error)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.node_api_create_syntax_error)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.node_api_create_syntax_error)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.node_api_create_syntax_error)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.node_api_create_syntax_error), "node_api_create_syntax_error", &symbols.node_api_create_syntax_error);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn node_api_symbol_for(
    arg0: @typeInfo(@TypeOf(n.node_api_symbol_for)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.node_api_symbol_for)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.node_api_symbol_for)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.node_api_symbol_for)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.node_api_symbol_for)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.node_api_symbol_for), "node_api_symbol_for", &symbols.node_api_symbol_for);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn node_api_throw_syntax_error(
    arg0: @typeInfo(@TypeOf(n.node_api_throw_syntax_error)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.node_api_throw_syntax_error)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.node_api_throw_syntax_error)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.node_api_throw_syntax_error)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.node_api_throw_syntax_error), "node_api_throw_syntax_error", &symbols.node_api_throw_syntax_error);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_get_node_version(
    arg0: @typeInfo(@TypeOf(n.napi_get_node_version)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_node_version)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_get_node_version)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_node_version), "napi_get_node_version", &symbols.napi_get_node_version);
    return ptr(arg0, arg1);
}
pub export fn napi_get_version(
    arg0: @typeInfo(@TypeOf(n.napi_get_version)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_version)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_get_version)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_version), "napi_get_version", &symbols.napi_get_version);
    return ptr(arg0, arg1);
}
pub export fn napi_get_uv_event_loop(
    arg0: @typeInfo(@TypeOf(n.napi_get_uv_event_loop)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_get_uv_event_loop)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.napi_get_uv_event_loop)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_get_uv_event_loop), "napi_get_uv_event_loop", &symbols.napi_get_uv_event_loop);
    return ptr(arg0, arg1);
}
pub export fn napi_run_script(
    arg0: @typeInfo(@TypeOf(n.napi_run_script)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_run_script)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_run_script)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_run_script)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_run_script), "napi_run_script", &symbols.napi_run_script);
    return ptr(arg0, arg1, arg2);
}
pub export fn napi_strict_equals(
    arg0: @typeInfo(@TypeOf(n.napi_strict_equals)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_strict_equals)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_strict_equals)).@"fn".params[2].type.?,
    arg3: @typeInfo(@TypeOf(n.napi_strict_equals)).@"fn".params[3].type.?,
) @typeInfo(@TypeOf(n.napi_strict_equals)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_strict_equals), "napi_strict_equals", &symbols.napi_strict_equals);
    return ptr(arg0, arg1, arg2, arg3);
}
pub export fn napi_typeof(
    arg0: @typeInfo(@TypeOf(n.napi_typeof)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.napi_typeof)).@"fn".params[1].type.?,
    arg2: @typeInfo(@TypeOf(n.napi_typeof)).@"fn".params[2].type.?,
) @typeInfo(@TypeOf(n.napi_typeof)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.napi_typeof), "napi_typeof", &symbols.napi_typeof);
    return ptr(arg0, arg1, arg2);
}
pub export fn node_api_get_module_file_name(
    arg0: @typeInfo(@TypeOf(n.node_api_get_module_file_name)).@"fn".params[0].type.?,
    arg1: @typeInfo(@TypeOf(n.node_api_get_module_file_name)).@"fn".params[1].type.?,
) @typeInfo(@TypeOf(n.node_api_get_module_file_name)).@"fn".return_type.? {
    const ptr = resolve(@TypeOf(n.node_api_get_module_file_name), "node_api_get_module_file_name", &symbols.node_api_get_module_file_name);
    return ptr(arg0, arg1);
}
