export fn napi_acquire_threadsafe_function() void {}
export fn napi_add_async_cleanup_hook() void {}
export fn napi_add_env_cleanup_hook() void {}
export fn napi_add_finalizer() void {}
export fn napi_adjust_external_memory() void {}
export fn napi_async_destroy() void {}
export fn napi_async_init() void {}
export fn napi_call_function() void {}
export fn napi_call_threadsafe_function() void {}
export fn napi_cancel_async_work() void {}
export fn napi_check_object_type_tag() void {}
export fn napi_close_callback_scope() void {}
export fn napi_close_escapable_handle_scope() void {}
export fn napi_close_handle_scope() void {}
export fn napi_coerce_to_bool() void {}
export fn napi_coerce_to_number() void {}
export fn napi_coerce_to_object() void {}
export fn napi_coerce_to_string() void {}
export fn napi_create_array() void {}
export fn napi_create_array_with_length() void {}
export fn napi_create_arraybuffer() void {}
export fn napi_create_async_work() void {}
export fn napi_create_bigint_int64() void {}
export fn napi_create_bigint_uint64() void {}
export fn napi_create_bigint_words() void {}
export fn napi_create_buffer() void {}
export fn napi_create_buffer_copy() void {}
export fn napi_create_dataview() void {}
export fn napi_create_date() void {}
export fn napi_create_double() void {}
export fn napi_create_error() void {}
export fn napi_create_external() void {}
export fn napi_create_external_arraybuffer() void {}
export fn napi_create_external_buffer() void {}
export fn napi_create_function() void {}
export fn napi_create_int32() void {}
export fn napi_create_int64() void {}
export fn napi_create_object() void {}
export fn napi_create_promise() void {}
export fn napi_create_range_error() void {}
export fn napi_create_reference() void {}
export fn napi_create_string_latin1() void {}
export fn napi_create_string_utf16() void {}
export fn napi_create_string_utf8() void {}
export fn napi_create_symbol() void {}
export fn napi_create_threadsafe_function() void {}
export fn napi_create_type_error() void {}
export fn napi_create_typedarray() void {}
export fn napi_create_uint32() void {}
export fn napi_define_class() void {}
export fn napi_define_properties() void {}
export fn napi_delete_async_work() void {}
export fn napi_delete_element() void {}
export fn napi_delete_property() void {}
export fn napi_delete_reference() void {}
export fn napi_detach_arraybuffer() void {}
export fn napi_escape_handle() void {}
export fn napi_fatal_error() void {}
export fn napi_fatal_exception() void {}
export fn napi_get_all_property_names() void {}
export fn napi_get_and_clear_last_exception() void {}
export fn napi_get_array_length() void {}
export fn napi_get_arraybuffer_info() void {}
export fn napi_get_boolean() void {}
export fn napi_get_buffer_info() void {}
export fn napi_get_cb_info() void {}
export fn napi_get_dataview_info() void {}
export fn napi_get_date_value() void {}
export fn napi_get_element() void {}
export fn napi_get_global() void {}
export fn napi_get_instance_data() void {}
export fn napi_get_last_error_info() void {}
export fn napi_get_named_property() void {}
export fn napi_get_new_target() void {}
export fn napi_get_null() void {}
export fn napi_get_property() void {}
export fn napi_get_property_names() void {}
export fn napi_get_prototype() void {}
export fn napi_get_reference_value() void {}
export fn napi_get_threadsafe_function_context() void {}
export fn napi_get_typedarray_info() void {}
export fn napi_get_undefined() void {}
export fn napi_get_value_bigint_int64() void {}
export fn napi_get_value_bigint_uint64() void {}
export fn napi_get_value_bigint_words() void {}
export fn napi_get_value_bool() void {}
export fn napi_get_value_double() void {}
export fn napi_get_value_external() void {}
export fn napi_get_value_int32() void {}
export fn napi_get_value_int64() void {}
export fn napi_get_value_string_latin1() void {}
export fn napi_get_value_string_utf16() void {}
export fn napi_get_value_string_utf8() void {}
export fn napi_get_value_uint32() void {}
export fn napi_has_element() void {}
export fn napi_has_named_property() void {}
export fn napi_has_own_property() void {}
export fn napi_has_property() void {}
export fn napi_instanceof() void {}
export fn napi_is_array() void {}
export fn napi_is_arraybuffer() void {}
export fn napi_is_buffer() void {}
export fn napi_is_dataview() void {}
export fn napi_is_date() void {}
export fn napi_is_detached_arraybuffer() void {}
export fn napi_is_error() void {}
export fn napi_is_exception_pending() void {}
export fn napi_is_promise() void {}
export fn napi_is_typedarray() void {}
export fn napi_make_callback() void {}
export fn napi_new_instance() void {}
export fn napi_object_freeze() void {}
export fn napi_object_seal() void {}
export fn napi_open_callback_scope() void {}
export fn napi_open_escapable_handle_scope() void {}
export fn napi_open_handle_scope() void {}
export fn napi_queue_async_work() void {}
export fn napi_ref_threadsafe_function() void {}
export fn napi_reference_ref() void {}
export fn napi_reference_unref() void {}
export fn napi_reject_deferred() void {}
export fn napi_release_threadsafe_function() void {}
export fn napi_remove_async_cleanup_hook() void {}
export fn napi_remove_env_cleanup_hook() void {}
export fn napi_remove_wrap() void {}
export fn napi_resolve_deferred() void {}
export fn napi_set_element() void {}
export fn napi_set_instance_data() void {}
export fn napi_set_named_property() void {}
export fn napi_set_property() void {}
export fn napi_throw() void {}
export fn napi_throw_error() void {}
export fn napi_throw_range_error() void {}
export fn napi_throw_type_error() void {}
export fn napi_type_tag_object() void {}
export fn napi_unref_threadsafe_function() void {}
export fn napi_unwrap() void {}
export fn napi_wrap() void {}
export fn node_api_create_buffer_from_arraybuffer() void {}
export fn node_api_create_external_string_latin1() void {}
export fn node_api_create_external_string_utf16() void {}
export fn node_api_create_property_key_latin1() void {}
export fn node_api_create_property_key_utf16() void {}
export fn node_api_create_property_key_utf8() void {}
export fn node_api_create_syntax_error() void {}
export fn node_api_symbol_for() void {}
export fn node_api_throw_syntax_error() void {}
export fn napi_get_node_version() void {}
export fn napi_get_version() void {}
export fn napi_get_uv_event_loop() void {}
export fn napi_run_script() void {}
export fn napi_strict_equals() void {}
export fn napi_typeof() void {}
export fn node_api_get_module_file_name() void {}
